### ISSUE TITLE
LoLUpdated crashes on clicking install

### ISSUE THREAD

**Issue by DarkhShadow** [Loggan08/LoLUpdater#15]
Windows 8.1
Everytime I select the league folder and install it crashes a few moments later.

Event viewer log

"Fault bucket 81808354072, type 5
Event Name: BEX
Response: Not available
Cab Id: 0

Problem signature:
P1: LoLUpdater.exe
P2: 1.0.2.1
P3: 54db8a8e
P4: LoLUpdater.exe
P5: 1.0.2.1
P6: 54db8a8e
P7: 0000bbd5
P8: c0000409
P9: 00000007
P10: 

Attached files:
C:\Users\Jacob\AppData\Local\Temp\WERE133.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_LoLUpdater.exe_b8a5a9ef4b79f5d723d3cb1180397fa5941ad_5ad3ab21_ef21e6f0

Analysis symbol: 
Rechecking for solution: 0
Report ID: 1442c16e-b217-11e4-82ba-18cf5e24a5a5
Report Status: 0
Hashed bucket: b1b169815f98b295c3649d370045ead1"

"Faulting application name: LoLUpdater.exe, version: 1.0.2.1, time stamp: 0x54db8a8e
Faulting module name: LoLUpdater.exe, version: 1.0.2.1, time stamp: 0x54db8a8e
Exception code: 0xc0000409
Fault offset: 0x0000bbd5
Faulting process ID: 0xf2ac
Faulting application start time: 0x01d04624234991e7
Faulting application path: C:\Users\Jacob\Downloads\LoLUpdater.exe
Faulting module path: C:\Users\Jacob\Downloads\LoLUpdater.exe
Report ID: 75faf2af-b217-11e4-82ba-18cf5e24a5a5
Faulting package full name: 
Faulting package-relative application ID: "

**Comment by Loggan08** [comment]
Alright, will have a look at it once im done with the new GUI

**Comment by Loggan08** [comment]
Fixed

**Comment by Loggan08** [comment]
Fixed


Skickat från min Samsung-enhet


-------- Originalmeddelande --------
Från: DarkhShadow <notifications@github.com> 
Datum: 11-02-2015  19:04  (GMT+01:00) 
Till: Loggan08/LoLUpdater <LoLUpdater@noreply.github.com> 
Rubrik: [LoLUpdater] LoLUpdated crashes on clicking install (#15) 

Windows 8.1
Everytime I select the league folder and install it crashes a few moments later.

Event viewer log

"Fault bucket 81808354072, type 5
Event Name: BEX
Response: Not available
Cab Id: 0

Problem signature:
P1: LoLUpdater.exe
P2: 1.0.2.1
P3: 54db8a8e
P4: LoLUpdater.exe
P5: 1.0.2.1
P6: 54db8a8e
P7: 0000bbd5
P8: c0000409
P9: 00000007
P10:

Attached files:
C:\Users\Jacob\AppData\Local\Temp\WERE133.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_LoLUpdater.exe_b8a5a9ef4b79f5d723d3cb1180397fa5941ad_5ad3ab21_ef21e6f0

Analysis symbol: 
Rechecking for solution: 0
Report ID: 1442c16e-b217-11e4-82ba-18cf5e24a5a5
Report Status: 0
Hashed bucket: b1b169815f98b295c3649d370045ead1"

"Faulting application name: LoLUpdater.exe, version: 1.0.2.1, time stamp: 0x54db8a8e
Faulting module name: LoLUpdater.exe, version: 1.0.2.1, time stamp: 0x54db8a8e
Exception code: 0xc0000409
Fault offset: 0x0000bbd5
Faulting process ID: 0xf2ac
Faulting application start time: 0x01d04624234991e7
Faulting application path: C:\Users\Jacob\Downloads\LoLUpdater.exe
Faulting module path: C:\Users\Jacob\Downloads\LoLUpdater.exe
Report ID: 75faf2af-b217-11e4-82ba-18cf5e24a5a5
Faulting package full name: 
Faulting package-relative application ID: "
