### ISSUE TITLE
Crashes shortly after clicking install.

### ISSUE THREAD

**Issue by DarkhShadow** [Loggan08/LoLUpdater#16]
Windows 8.1

Appears to start patching but then crashes.

"Problem signature:
  Problem Event Name:	BEX
  Application Name:	LoLUpdater.exe
  Application Version:	1.0.6.7
  Application Timestamp:	5511d398
  Fault Module Name:	LoLUpdater.exe
  Fault Module Version:	1.0.6.7
  Fault Module Timestamp:	5511d398
  Exception Offset:	000116fe
  Exception Code:	c0000409
  Exception Data:	00000007
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	2057
  Additional Information 1:	7f74
  Additional Information 2:	7f747e681f718af39491bc53a68717b4
  Additional Information 3:	4db5
  Additional Information 4:	4db57ea8030ef2343fbe116983f46d21

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\windows\system32\en-GB\erofflps.txt
"

**Comment by Loggan08** [comment]
Delete everything in C:\Windows\Temp

Uninstall all Adobe Flash (you will have to redownload these later unless
lolupdater does it automatically for you)
Then reboot and try again, updated the files btw.

**Comment by DarkhShadow** [comment]
After clearing out my temp folder and removing all Flash versions/rebooting it still crashes at the same stage.
Not sure if this is the same or different
"Problem signature:
  Problem Event Name:	BEX
  Application Name:	LoLUpdater1.0.6.8.exe
  Application Version:	1.0.6.8
  Application Timestamp:	5511f9ce
  Fault Module Name:	LoLUpdater1.0.6.8.exe
  Fault Module Version:	1.0.6.8
  Fault Module Timestamp:	5511f9ce
  Exception Offset:	000116fe
  Exception Code:	c0000409
  Exception Data:	00000007
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	2057
  Additional Information 1:	6a48
  Additional Information 2:	6a4816b55695de0ad4955542a5dd10e7
  Additional Information 3:	1be4
  Additional Information 4:	1be48692a8ccefe6c207da9f3f0b0d9b

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\windows\system32\en-GB\erofflps.txt
"

**Comment by Loggan08** [comment]
I will have a closer look at this tomorrow, you can add me on skype in the
meantime or join the IRC channel, time for me to go to bed now

**Comment by Loggan08** [comment]
If you have Firefox or any other browser running in the background see what
happens if you exit it and patch with lolupdater

**Comment by DarkhShadow** [comment]
After closing my browser (Firefox Dev version 64bit 38.0a2) it did succesfully patch this time.

**Comment by Loggan08** [comment]
Will add a notice about this
