### ISSUE TITLE
New update, post 1.1.5.3, does not work with LeagueSharp

### ISSUE THREAD

**Issue by PhantomL0rd** [Loggan08/LoLUpdater#18]
Causes issue injecting assemblies

**Comment by Loggan08** [comment]
Try installing it twice, ie again.

Otherwise you will have to delete the MSVCR120.dll file
in RADS\solutions\lol_game_client_sln\releases\0.0.1.85\deploy

**Comment by Loggan08** [comment]
or this one: https://www.joduska.me/forum/topic/58694-official-fix-for-lolupdater/?hl=%2Blolupdater+%2Bfix
