### ISSUE TITLE
Download page isn't working

### ISSUE THREAD

**Issue by Darker** [Loggan08/LoLUpdater#19]
Not sure if part of this project, but the release download page isn't working: https://lolupdater.com/?p=download

Also only assholes disable right click on their websites. This is a great addon to deal with these people:

**Comment by davidkna** [comment]
Here is the direct download url until this is fixed: http://www.smoothdev.org/mirrors/download.php?user=Loggan&file=T1VRdVdqb3daL1doZ1p6T1JWN3VvUT09

**Comment by NitroXenon** [comment]
@davidkna also down...

**Comment by Loggan08** [comment]
FTP being DDOSED atm
